services:

# ==========================================================
  # POSTGRESQL - METADATA DO AIRFLOW
  # ==========================================================
  airflow-postgres:
    image: postgres:16

    container_name: data-engineer-postgres-airflow

    restart: unless-stopped

    environment:
      POSTGRES_DB: ${AIRFLOW_DB}
      POSTGRES_USER: ${AIRFLOW_DB_USER}
      POSTGRES_PASSWORD: ${AIRFLOW_DB_PASSWORD}
      TZ: America/Araguaina

    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - /var/run/docker.sock:/var/run/docker.sock
    
    env_file:
      - ./.env

    networks:
      - data-engineer-network

  # ==========================================================
  # AIRFLOW INIT
  # Inicialização do banco e criação do usuário administrador
  # ==========================================================
  airflow-init:
    image: apache/airflow:2.10.5-python3.12

    container_name: data-engineer-airflow-init

    depends_on:
      airflow-postgres:
        condition: service_started

    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: >-
        postgresql+psycopg2://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASSWORD}@airflow-postgres:5432/${AIRFLOW_DB}
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      TZ: America/Araguaina

    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - /var/run/docker.sock:/var/run/docker.sock

    env_file:
      - ./.env

    command:
      - bash
      - -c
      - |
        airflow db migrate &&
        airflow users create \
          --username ${AIRFLOW_ADMIN_USERNAME} \
          --password ${AIRFLOW_ADMIN_PASSWORD} \
          --firstname ${AIRFLOW_ADMIN_FIRSTNAME} \
          --lastname ${AIRFLOW_ADMIN_LASTNAME} \
          --role Admin \
          --email ${AIRFLOW_ADMIN_EMAIL} || true

    networks:
      - data-engineer-network

  # ==========================================================
  # AIRFLOW WEBSERVER
  # Interface Web do Airflow
  # ==========================================================
  airflow-webserver:
    image: apache/airflow:2.10.5-python3.12

    container_name: data-engineer-airflow-webserver

    restart: unless-stopped

    depends_on:
      airflow-init:
        condition: service_completed_successfully

    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: >-
        postgresql+psycopg2://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASSWORD}@airflow-postgres:5432/${AIRFLOW_DB}
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__API__AUTH_BACKENDS: >-
        airflow.api.auth.backend.session
      TZ: America/Araguaina

    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - /var/run/docker.sock:/var/run/docker.sock

    env_file:
      - ./.env

    ports:
      - "8088:8080"

    command:
      - airflow
      - webserver

    networks:
      - data-engineer-network

    # ==========================================================
  # AIRFLOW SCHEDULER
  # Executa e agenda as DAGs
  # ==========================================================
  airflow-scheduler:
    image: apache/airflow:2.10.5-python3.12

    container_name: data-engineer-airflow-scheduler

    restart: unless-stopped

    depends_on:
      airflow-init:
        condition: service_completed_successfully

    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: >-
        postgresql+psycopg2://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASSWORD}@airflow-postgres:5432/${AIRFLOW_DB}
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      TZ: America/Araguaina

    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - /var/run/docker.sock:/var/run/docker.sock

    env_file:
      - ./.env

    command:
      - airflow
      - scheduler

    networks:
      - data-engineer-network

  # ==========================================================
  # POSTGRESQL
  # ==========================================================
  postgres:
    image: postgres:16
    container_name: data-engineer-postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: America/Araguaina

    ports:
      - ${POSTGRES_PORT}

    volumes:
      - postgres_data:/var/lib/postgresql/data

    env_file:
      - ./.env

    networks:
      - data-engineer-network

  # ==========================================================
  # PGADMIN 4 - INTERFACE GRÁFICA DO POSTGRESQL
  # ==========================================================
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: data-engineer-pgamdin

    restart: unless-stopped

    environment:
      # E-mail utilizado para entrar no pgAdmin
      PGADMIN_DEFAULT_EMAIL: thiago@gmail.com
      # Defina uma senha própria para o pgAdmin
      PGADMIN_DEFAULT_PASSWORD: 123
      TZ: America/Araguaina

    ports:
      # Acessar pelo navegador em http://localhost:5050
      - "5050:80"

    depends_on:
      - postgres

    env_file:
      - ./.env

    networks:
      - data-engineer-network 

  # ==========================================================
  # FINANCE CONSUMER
  # ==========================================================
  finance-consumer:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: data-engineer-api:1.0
    container_name: data-engineer-finance-consumer
    restart: unless-stopped

    env_file:
      - ./.env

    environment:
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      KAFKA_TOPIC: ${KAFKA_TOPIC}
      KAFKA_GROUP_ID: finance-consumer-group

      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - ./api:/app

    command:
      [
        "python",
        "-m",
        "app.consumers.finance_consumer"
      ]

    depends_on:
      - kafka
      - postgres

    networks:
      - data-engineer-network

  # ====================================
  # API
  # ====================================
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: data-engineer-api:1.0
    container_name: data-engineer-api

    restart: unless-stopped

    environment:
      TZ: America/Araguaina

    env_file:
    - ./.env

    ports:
      - "8000:8000"

    volumes:
      - ./api:/app

    command:
      [
        "uvicorn",
        "main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "--reload"
      ]

    networks:
      - data-engineer-network

  # ==========================================================
  # KAFKA
  # ==========================================================
  kafka:
      image: apache/kafka:latest
      container_name: data-engineer-kafka

      restart: unless-stopped

      ports:
        - "9092:9092"

      environment:
        # Identificador único do nó Kafka.
        KAFKA_NODE_ID: 1

        # Define as funções desse nó.
        #
        # broker:
        #     responsável pelas mensagens.
        #
        # controller:
        #     responsável pelo gerenciamento
        #     do cluster.
        #
        # Essa configuração utiliza KRaft,
        # portanto não precisamos de ZooKeeper.
        KAFKA_PROCESS_ROLES: broker,controller

        # Define o controller do cluster.
        #
        # kafka:9093 significa:
        #
        # container kafka
        # porta 9093
        KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

        # Define os listeners utilizados pelo Kafka.
        #
        # INTERNAL:
        # comunicação entre containers Docker.
        #
        # EXTERNAL:
        # comunicação entre o computador host
        # e o container.
        #
        # CONTROLLER:
        # comunicação de controle do Kafka.
        KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093

        # Endereços que o Kafka informa aos clientes.
        #
        # Dentro do Docker:
        # kafka:29092
        #
        # Fora do Docker:
        # localhost:9092
        KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092

        
        # Define o protocolo de cada listener.
        #
        # Neste projeto estamos utilizando
        # PLAINTEXT, ou seja, sem criptografia.
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT

        # Listener utilizado para comunicação entre brokers.
        KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

        # Listener utilizado pelo controller.
        KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

        # Como temos apenas um broker,
        # a replicação dos tópicos internos
        # precisa ser 1.
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

        # Fator de replicação do log de transações.
        KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

        # Número mínimo de réplicas sincronizadas.
        KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

        # Remove o atraso inicial de rebalanceamento do Consumer Group.
        KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
        
        TZ: America/Araguaina

      env_file:
        - ./.env
        
      networks:
        - data-engineer-network

  # ==========================================================
  # KAFKA UI - parte gráfica do Kafka
  # ==========================================================
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: data-engineer-kafkaUI

    # Reinicia automaticamente.
    restart: unless-stopped

    # Indica que o Kafka UI depende do Kafka.
    # O Docker iniciará o Kafka antes do Kafka UI.
    depends_on:
      - kafka

    ports:
      - "8080:8080"

    # --------------------------------------------------------
    # CONFIGURAÇÃO DO KAFKA UI
    # --------------------------------------------------------

    environment:
      # Nome que aparecerá na interface.
      KAFKA_CLUSTERS_0_NAME: finance.market

      # Endereço do Kafka dentro da rede Docker.
      #
      # IMPORTANTE:
      #
      # Aqui NÃO usamos localhost:9092.
      #
      # Como Kafka UI está dentro do Docker,
      # ele acessa o Kafka através do nome
      # do serviço:
      #
      # kafka:29092
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092

      TZ: America/Araguaina

    networks:
      - data-engineer-network
    
    env_file:
      - ./.env

# ==========================================================
# dbt
# ==========================================================
  dbt:
    build:
      context: ./dbt
      dockerfile: Dockerfile
    image: data-engineer-dbt:1.0
    container_name: data-engineer-dbt

    restart: "no"

    depends_on:
      postgres:
        condition: service_started

    environment:
      - TZ=America/Araguaina

    env_file:
      - ./.env

    volumes:
      - ./dbt:/usr/app/dbt

    working_dir: /usr/app/dbt

    command:
      - tail
      - -f
      - /dev/null

    networks:
      - data-engineer-network
      
# ==========================================================
  # VOLUME
  # ==========================================================
volumes:
  postgres_data:
  airflow_postgres_data:

# ==========================================================
  # NETWORKS
  # ==========================================================   
networks:
  data-engineer-network:
    driver: bridge
